name: moengage_task
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  states_rebuilder: ^5.2.0
  json_annotation: ^4.4.0
  retrofit: ^3.0.1
  logger: ^1.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  sprintf: ^6.0.0
  cached_network_image: ^3.2.0
  dartx: ^1.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.13
  connectivity_plus: ^2.2.0
  intl: ^0.17.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.0.4
  retrofit_generator: ^4.0.1
  json_serializable: ^6.0.0
  flutter_gen_runner: ^4.0.0
  hive_generator: ^1.1.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
